# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
    secret_key_base: b5d6d3130a46e3a690234a8c89ca7dd3b55f51b4fef589c3918513b19b8e6c83486bd2af15ccffefcb08ea3f19d3a7d43c22fd4bf4f24dc762b1d97b729869da
    paypal:
        username: merchant_api1.llprk.dev
        password: KEJHC7YCJFZMJUJJ
        signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AAu1-B79YKOzS2hITWcaTPGzS5-I
        sandbox: true
    old_connectionstring:
        username: meist
        password: Siebzehn17
        dataserver: p9s65l7agf.database.windows.net
        port: 1433
        database: llprk2ALCEJZIM0h
        azure: true

test:
    secret_key_base: cef82f2f945a673e791be0b77f9853cc29892763a294bfbf667104a75441e7fcad7164d724462ea1c46f3f4249ebff9923c5876d4b76477bfc8230f0c60f2d9c
    paypal:
        username: merchant_api1.llprk.dev
        password: KEJHC7YCJFZMJUJJ
        signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AAu1-B79YKOzS2hITWcaTPGzS5-I
        sandbox: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
    paypal:
        username: <%= ENV["PAYPAL_USERNAME"] %>
        password: <%= ENV["PAYPAL_PASSWORD"] %>
        signature: <%= ENV["PAYPAL_SIGNATURE"] %>
        sandbox: false
